apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME-app
          image: eu.gcr.io/$PROJECT_ID/$APP_NAME
          env:
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME-secrets
                  key: FLASK_SECRET_KEY
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME-secrets
                  key: CLIENT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME-postgresql
                  key: postgresql-password
          resources:
            requests:
              cpu: "25m"
